version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: prdev_app
    volumes:
      - ./app:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - database
  database:
    image: mysql:8.0.29-debian
    container_name: prdev_db
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prdev_db
      MYSQL_USER: prdev
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prdev_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - database
volumes:
  db_data: {}